version: '3'

services:
  mongo:
    ports:
      - "27017:27017"
  eventstore:
    ports:
      - "2113:2113"
      - "1113:1113"
  eventsourcingcqrs:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
